name: Fennlingo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.1

    # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo-removebg-preview.png
    - assets/logo/mascotte.png
    - assets/logo/mascotte_tete.png
    - assets/images/athletes/

# Configuration des icônes (au niveau racine, PAS sous flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo-removebg-preview"  # Image principale (1024x1024 px)
  adaptive_icon_foreground: "assets/icons/logo-removebg-preview"  # Version simplifiée (432x432 px)
  adaptive_icon_background: "#FFFFFF"

# Activate developer mode for Windows
# Run this command in PowerShell:
# start ms-settings:developers